name: Deploy Static Site

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up Go (optional, if your static site generator is written in Go)
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # Step 3: Build the static site (if applicable)
    - name: Build site
      run: go run main.go

    # Step 4: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./output  # Directory where your static files are located
